//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vkazo.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vkazo.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VKAZO.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verband.
        /// </summary>
        internal static string Association {
            get {
                return ResourceManager.GetString("Association", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausbildung.
        /// </summary>
        internal static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einsätze.
        /// </summary>
        internal static string Einsaetze {
            get {
                return ResourceManager.GetString("Einsaetze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinwil Badi.
        /// </summary>
        internal static string HinwilBadi {
            get {
                return ResourceManager.GetString("HinwilBadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Einsatz für die Badi Hinwil.
        /// </summary>
        internal static string HinwilBadiDescription {
            get {
                return ResourceManager.GetString("HinwilBadiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinwil Rock the Ring.
        /// </summary>
        internal static string HinwilRocKTheRing {
            get {
                return ResourceManager.GetString("HinwilRocKTheRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die VKZO rockt den Ring.
        /// </summary>
        internal static string HinwilRocKTheRingDescription {
            get {
                return ResourceManager.GetString("HinwilRocKTheRingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to badi.png.
        /// </summary>
        internal static string ImageHinwilBadi {
            get {
                return ResourceManager.GetString("ImageHinwilBadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liveatsunset.png.
        /// </summary>
        internal static string ImageLiveAtSunset {
            get {
                return ResourceManager.GetString("ImageLiveAtSunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rockthering.png.
        /// </summary>
        internal static string ImageRockTheRing {
            get {
                return ResourceManager.GetString("ImageRockTheRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zoo.png.
        /// </summary>
        internal static string ImageZurichZoo {
            get {
                return ResourceManager.GetString("ImageZurichZoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live at Sunset.
        /// </summary>
        internal static string LiveAtSunset {
            get {
                return ResourceManager.GetString("LiveAtSunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vks beim Sunset in Zürich.
        /// </summary>
        internal static string LiveAtSunsetDescription {
            get {
                return ResourceManager.GetString("LiveAtSunsetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verein.
        /// </summary>
        internal static string Organisations {
            get {
                return ResourceManager.GetString("Organisations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsere Einsätze.
        /// </summary>
        internal static string UnsereEinsaetze {
            get {
                return ResourceManager.GetString("UnsereEinsaetze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zürich Zoo.
        /// </summary>
        internal static string ZurichZoo {
            get {
                return ResourceManager.GetString("ZurichZoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einsatz beim Zürcher Zoo.
        /// </summary>
        internal static string ZurichZooDescription {
            get {
                return ResourceManager.GetString("ZurichZooDescription", resourceCulture);
            }
        }
    }
}
