//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vkazo.Resources.Education {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GradeLessonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GradeLessonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vkazo.Resources.Education.GradeLessonResources", typeof(GradeLessonResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asp.
        /// </summary>
        internal static string Asp {
            get {
                return ResourceManager.GetString("Asp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AspImage {
            get {
                return ResourceManager.GetString("AspImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspirant.
        /// </summary>
        internal static string AspLong {
            get {
                return ResourceManager.GetString("AspLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gfr.
        /// </summary>
        internal static string Gfr {
            get {
                return ResourceManager.GetString("Gfr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GfrImage {
            get {
                return ResourceManager.GetString("GfrImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gefreiter.
        /// </summary>
        internal static string GfrLong {
            get {
                return ResourceManager.GetString("GfrLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kpl.
        /// </summary>
        internal static string Kpl {
            get {
                return ResourceManager.GetString("Kpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string KplImage {
            get {
                return ResourceManager.GetString("KplImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korporal.
        /// </summary>
        internal static string KplLong {
            get {
                return ResourceManager.GetString("KplLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vk.
        /// </summary>
        internal static string Vk {
            get {
                return ResourceManager.GetString("Vk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VkImage {
            get {
                return ResourceManager.GetString("VkImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkehrskadett.
        /// </summary>
        internal static string VkLong {
            get {
                return ResourceManager.GetString("VkLong", resourceCulture);
            }
        }
    }
}
