//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vkazo.Resources.Education {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GradeLessonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GradeLessonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vkazo.Resources.Education.GradeLessonResources", typeof(GradeLessonResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adj.
        /// </summary>
        internal static string Adj {
            get {
                return ResourceManager.GetString("Adj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adjudant.png.
        /// </summary>
        internal static string AdjImage {
            get {
                return ResourceManager.GetString("AdjImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjudant Stab.
        /// </summary>
        internal static string AdjLong {
            get {
                return ResourceManager.GetString("AdjLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asp.
        /// </summary>
        internal static string Asp {
            get {
                return ResourceManager.GetString("Asp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AspImage {
            get {
                return ResourceManager.GetString("AspImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspirant.
        /// </summary>
        internal static string AspLong {
            get {
                return ResourceManager.GetString("AspLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gfr.
        /// </summary>
        internal static string Gfr {
            get {
                return ResourceManager.GetString("Gfr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gefreiter.png.
        /// </summary>
        internal static string GfrImage {
            get {
                return ResourceManager.GetString("GfrImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gefreiter.
        /// </summary>
        internal static string GfrLong {
            get {
                return ResourceManager.GetString("GfrLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hptm.
        /// </summary>
        internal static string Hptm {
            get {
                return ResourceManager.GetString("Hptm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hauptmann.png.
        /// </summary>
        internal static string HptmImage {
            get {
                return ResourceManager.GetString("HptmImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hautpmann.
        /// </summary>
        internal static string HptmLong {
            get {
                return ResourceManager.GetString("HptmLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kpl.
        /// </summary>
        internal static string Kpl {
            get {
                return ResourceManager.GetString("Kpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to korporal.png.
        /// </summary>
        internal static string KplImage {
            get {
                return ResourceManager.GetString("KplImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korporal.
        /// </summary>
        internal static string KplLong {
            get {
                return ResourceManager.GetString("KplLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lt.
        /// </summary>
        internal static string Lt {
            get {
                return ResourceManager.GetString("Lt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leutnant.png.
        /// </summary>
        internal static string LtImage {
            get {
                return ResourceManager.GetString("LtImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leutnant.
        /// </summary>
        internal static string LtLong {
            get {
                return ResourceManager.GetString("LtLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maj.
        /// </summary>
        internal static string Maj {
            get {
                return ResourceManager.GetString("Maj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to major.png.
        /// </summary>
        internal static string MajImage {
            get {
                return ResourceManager.GetString("MajImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        internal static string MajLong {
            get {
                return ResourceManager.GetString("MajLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oberst.
        /// </summary>
        internal static string Oberst {
            get {
                return ResourceManager.GetString("Oberst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oberst.png.
        /// </summary>
        internal static string OberstImage {
            get {
                return ResourceManager.GetString("OberstImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oberst.
        /// </summary>
        internal static string OberstLong {
            get {
                return ResourceManager.GetString("OberstLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oberlt.
        /// </summary>
        internal static string Oberstlt {
            get {
                return ResourceManager.GetString("Oberstlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oberstleutnant.png.
        /// </summary>
        internal static string OberstltImage {
            get {
                return ResourceManager.GetString("OberstltImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oberstleutnant.
        /// </summary>
        internal static string OberstltLong {
            get {
                return ResourceManager.GetString("OberstltLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblt.
        /// </summary>
        internal static string Oblt {
            get {
                return ResourceManager.GetString("Oblt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oberleutnant.png.
        /// </summary>
        internal static string ObltImage {
            get {
                return ResourceManager.GetString("ObltImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oberleutnant.
        /// </summary>
        internal static string ObltLong {
            get {
                return ResourceManager.GetString("ObltLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Präsident.
        /// </summary>
        internal static string Praesident {
            get {
                return ResourceManager.GetString("Praesident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to praesident.png.
        /// </summary>
        internal static string PraesidentImage {
            get {
                return ResourceManager.GetString("PraesidentImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korpskommandant.
        /// </summary>
        internal static string PraesidentLong {
            get {
                return ResourceManager.GetString("PraesidentLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vk.
        /// </summary>
        internal static string Vk {
            get {
                return ResourceManager.GetString("Vk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vk.png.
        /// </summary>
        internal static string VkImage {
            get {
                return ResourceManager.GetString("VkImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkehrskadett.
        /// </summary>
        internal static string VkLong {
            get {
                return ResourceManager.GetString("VkLong", resourceCulture);
            }
        }
    }
}
