//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vkazo.Resources.Education {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MaterialLessonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaterialLessonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vkazo.Resources.Education.MaterialLessonResources", typeof(MaterialLessonResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blitzlampe.
        /// </summary>
        internal static string Flashlamp {
            get {
                return ResourceManager.GetString("Flashlamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FlashlampDescription {
            get {
                return ResourceManager.GetString("FlashlampDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FlashlampImage {
            get {
                return ResourceManager.GetString("FlashlampImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faltsignal.
        /// </summary>
        internal static string FoldingTrafficSignal {
            get {
                return ResourceManager.GetString("FoldingTrafficSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FoldingTrafficSignalDescription {
            get {
                return ResourceManager.GetString("FoldingTrafficSignalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FoldingTrafficSignalImage {
            get {
                return ResourceManager.GetString("FoldingTrafficSignalImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scherengitter.
        /// </summary>
        internal static string ScissorLattice {
            get {
                return ResourceManager.GetString("ScissorLattice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ScissorLatticeDescription {
            get {
                return ResourceManager.GetString("ScissorLatticeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ScissorLatticeImage {
            get {
                return ResourceManager.GetString("ScissorLatticeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leitkegel, Tözli.
        /// </summary>
        internal static string TrafficCone {
            get {
                return ResourceManager.GetString("TrafficCone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrafficConeDescription {
            get {
                return ResourceManager.GetString("TrafficConeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrafficConeImage {
            get {
                return ResourceManager.GetString("TrafficConeImage", resourceCulture);
            }
        }
    }
}
